/* Generated by sol-shell from export/gtk.css.tpl. Edit the template, not this
   file: it is rewritten whenever the theme changes. GTK3 programs (Thunar) read it
   as ~/.config/gtk-3.0/gtk.css, which is a link to this file.
   The built-in Adwaita theme ignores redefined named colors (@define-color), so
   each kind of widget is colored by an explicit rule here. */

/* ---- windows, bars and menus ---- */

/* The main background is see-through (the opacity setting); Hyprland blurs what shows
   through. Dialogs stay solid. */
window,
.background {
    background-color: {{backgroundAlpha}};
    color: {{text}};
}

window.dialog,
dialog {
    background-color: {{window}};
    color: {{text}};
}

menubar,
toolbar,
.toolbar,
.inline-toolbar,
headerbar,
.titlebar,
statusbar,
actionbar {
    background-color: {{windowAlpha}};
    background-image: none;
    color: {{text}};
    border-color: {{border}};
    box-shadow: none;
}

statusbar label {
    color: {{subtext}};
}

menu,
.menu,
.popup,
popover,
popover.background,
tooltip,
tooltip.background {
    background-color: {{window}};
    background-image: none;
    color: {{text}};
    border: 1px solid {{border}};
}

menuitem:hover,
menuitem:selected,
modelbutton:hover {
    background-color: {{accent}};
    color: {{accentText}};
}

menuitem:hover label,
menuitem:selected label {
    color: {{accentText}};
}

separator {
    background-color: {{border}};
    color: {{border}};
}

/* ---- the file area and the side panel ---- */

.view,
iconview,
treeview.view {
    /* transparent: the window behind it already has the see-through background */
    background-color: transparent;
    color: {{text}};
}

textview,
textview text,
list,
row {
    background-color: {{background}};
    color: {{text}};
}

placessidebar,
placessidebar .view,
placessidebar list,
placessidebar row,
.sidebar,
.sidebar .view {
    background-color: {{windowAlpha}};
    color: {{text}};
}

.view:selected,
iconview:selected,
treeview.view:selected,
row:selected,
placessidebar row:selected,
.sidebar row:selected,
selection,
*:selected {
    background-color: {{accent}};
    color: {{accentText}};
}

row:hover,
placessidebar row:hover,
.view:hover {
    background-color: {{surface}};
}

treeview header button {
    background-color: {{window}};
    color: {{subtext}};
    border-color: {{border}};
}

/* ---- buttons and entries ---- */

button,
.button {
    background-image: none;
    background-color: {{surface}};
    color: {{text}};
    border: 1px solid {{border}};
    box-shadow: none;
    text-shadow: none;
}

button:hover {
    border-color: {{accent}};
}

button:checked,
button:active {
    background-color: {{accent}};
    color: {{accentText}};
}

button:disabled,
*:disabled {
    color: {{muted}};
}

entry,
spinbutton,
combobox button {
    background-image: none;
    background-color: {{surface}};
    color: {{text}};
    border: 1px solid {{border}};
    box-shadow: none;
}

entry:focus {
    border-color: {{accent}};
}

entry selection {
    background-color: {{accent}};
    color: {{accentText}};
}

/* ---- scrollbars ---- */

scrollbar,
scrollbar trough {
    background-color: transparent;
    border-color: transparent;
}

scrollbar slider {
    background-color: {{muted}};
    border-radius: 6px;
}

scrollbar slider:hover {
    background-color: {{subtext}};
}

paned > separator {
    background-color: {{border}};
}
