/* Generated by sol-shell from export/gtk.css.tpl. Edit the template, not this
   file: it is rewritten whenever the theme changes. GTK3 programs (Thunar) read it
   as ~/.config/gtk-3.0/gtk.css, which is a link to this file.
   The built-in Adwaita theme ignores redefined named colors (@define-color), so
   each kind of widget is colored by an explicit rule here. */

/* ---- windows, bars and menus ---- */

/* The main background is see-through (the opacity setting); Hyprland blurs what shows
   through. Dialogs stay solid. */
window,
.background {
    background-color: {{backgroundAlpha}};
    color: {{text}};
}

window.dialog,
dialog {
    background-color: {{window}};
    color: {{text}};
}

menubar,
toolbar,
.toolbar,
.inline-toolbar,
headerbar,
.titlebar,
statusbar,\
actionbar {
    background-color: {{windowAlpha}};
    background-image: none;
    color: {{text}};
    border-color: {{border}};
    box-shadow: none;
}

statusbar label {
    color: {{subtext}};
}

menu,
.menu,
.popup,
popover,
popover.background,
tooltip,
tooltip.background {
    background-color: {{window}};
    background-image: none;
    color: {{text}};
    border: 1px solid {{border}};
}

/* Menu items get their color from the theme directly (a dark grey), so the color set
   on the menu itself is not enough: it has to be set on the items. Order matters:
   normal, then disabled, then the highlighted one.

   The text of an item is not colored by its own rule: a label simply takes the color
   of its item (the theme says "inherit"). Rules like "menuitem:selected label" must
   NOT be used: the dropdown of a menu bar entry sits inside that entry in GTK's
   style tree, and the entry is "selected" while its dropdown is open, so such a rule
   would also color every label in the dropdown. */
menuitem,
menu menuitem,
menubar > menuitem {
    color: {{text}};
}

menubar > menuitem > label {
    color: inherit;
}

/* the shortcut at the right: the color of the item, a bit dimmer */
menuitem accelerator {
    color: alpha(currentColor, 0.7);
}

menuitem:disabled,
menu menuitem:disabled,
menubar > menuitem:disabled {
    color: {{muted}};
}

menuitem:hover,
menuitem:selected,
modelbutton:hover,
menu menuitem:hover,
menubar > menuitem:hover {
    background-color: {{accent}};
    color: {{accentText}};
    /* the theme draws a blue line under a highlighted menu bar entry */
    box-shadow: none;
}

separator {
    background-color: {{border}};
    color: {{border}};
}

/* ---- the file area and the side panel ---- */

.view,
iconview,
treeview.view {
    /* transparent: the window behind it already has the see-through background */
    background-color: transparent;
    color: {{text}};
}

textview,
textview text,
list,
row {
    background-color: {{background}};
    color: {{text}};
}

placessidebar,
placessidebar .view,
placessidebar list,
placessidebar row,
.sidebar,
.sidebar .view {
    background-color: {{windowAlpha}};
    color: {{text}};
}

.view:selected,
iconview:selected,
treeview.view:selected,
row:selected,
placessidebar row:selected,
.sidebar row:selected,
selection,
*:selected {
    background-color: {{accent}};
    color: {{accentText}};
}

row:hover,
placessidebar row:hover,
.view:hover {
    background-color: {{surface}};
}

treeview header button {
    background-color: {{window}};
    color: {{subtext}};
    border-color: {{border}};
}

/* ---- buttons and entries ---- */

button,
.button {
    background-image: none;
    background-color: {{surface}};
    color: {{text}};
    border: 1px solid {{border}};
    box-shadow: none;
    text-shadow: none;
}

button:hover {
    border-color: {{accent}};
}

button:checked,
button:active {
    background-color: {{accent}};
    color: {{accentText}};
}

button:disabled,
*:disabled {
    color: {{muted}};
}

entry,
spinbutton,
combobox button {
    background-image: none;
    background-color: {{surface}};
    color: {{text}};
    border: 1px solid {{border}};
    box-shadow: none;
}

entry:focus {
    border-color: {{accent}};
}

entry selection {
    background-color: {{accent}};
    color: {{accentText}};
}

/* ---- tabbed pages (the Preferences and Properties dialogs) ---- */

notebook > header {
    background-color: {{window}};
    border-color: {{border}};
}

notebook > header tab {
    color: {{subtext}};
}

notebook > header tab:hover {
    color: {{text}};
    background-color: {{surface}};
}

notebook > header tab:checked {
    color: {{text}};
}

/* the line under (or beside) the tab: grey on hover, the accent on the open tab */
notebook > header.top > tabs > tab:hover {
    box-shadow: inset 0 -4px {{border}};
}

notebook > header.top > tabs > tab:checked {
    box-shadow: inset 0 -4px {{accent}};
}

notebook > header.bottom > tabs > tab:hover {
    box-shadow: inset 0 4px {{border}};
}

notebook > header.bottom > tabs > tab:checked {
    box-shadow: inset 0 4px {{accent}};
}

notebook > header.left > tabs > tab:hover {
    box-shadow: inset -4px 0 {{border}};
}

notebook > header.left > tabs > tab:checked {
    box-shadow: inset -4px 0 {{accent}};
}

notebook > header.right > tabs > tab:hover {
    box-shadow: inset 4px 0 {{border}};
}

notebook > header.right > tabs > tab:checked {
    box-shadow: inset 4px 0 {{accent}};
}

/* the page itself, which the theme paints white */
notebook > stack:not(:only-child) {
    background-color: {{background}};
}

frame > border,
.frame {
    border-color: {{border}};
}

/* ---- scrollbars ---- */

scrollbar,
scrollbar trough {
    background-color: transparent;
    border-color: transparent;
}

scrollbar slider {
    background-color: {{muted}};
    border-radius: 6px;
}

scrollbar slider:hover {
    background-color: {{subtext}};
}

paned > separator {
    background-color: {{border}};
}
