# Generated by sol-shell from export/kdeglobals.tpl. Edit the template, not this
# file: it is rewritten whenever the theme changes. KDE programs (Dolphin) read it
# as ~/.config/kdeglobals, and as the color scheme "SolShell" through
# ~/.local/share/color-schemes/SolShell.colors. Link both paths to this file once
# (see the README).

[General]
ColorScheme=SolShell

[UiSettings]
ColorScheme=SolShell

[Colors:View]
BackgroundNormal={{backgroundRgb}}
BackgroundAlternate={{windowRgb}}
DecorationFocus={{accentRgb}}
DecorationHover={{accentHoverRgb}}
ForegroundNormal={{textRgb}}
ForegroundActive={{accentRgb}}
ForegroundInactive={{mutedRgb}}
ForegroundLink={{accentRgb}}
ForegroundVisited={{subtextRgb}}
ForegroundNegative={{dangerRgb}}
ForegroundNeutral={{accentRgb}}
ForegroundPositive={{successRgb}}

[Colors:Window]
BackgroundNormal={{windowRgb}}
BackgroundAlternate={{backgroundRgb}}
DecorationFocus={{accentRgb}}
DecorationHover={{accentHoverRgb}}
ForegroundNormal={{textRgb}}
ForegroundActive={{accentRgb}}
ForegroundInactive={{mutedRgb}}
ForegroundLink={{accentRgb}}
ForegroundVisited={{subtextRgb}}
ForegroundNegative={{dangerRgb}}
ForegroundNeutral={{accentRgb}}
ForegroundPositive={{successRgb}}

[Colors:Button]
BackgroundNormal={{surfaceRgb}}
BackgroundAlternate={{windowRgb}}
DecorationFocus={{accentRgb}}
DecorationHover={{accentHoverRgb}}
ForegroundNormal={{textRgb}}
ForegroundActive={{accentRgb}}
ForegroundInactive={{mutedRgb}}
ForegroundLink={{accentRgb}}
ForegroundVisited={{subtextRgb}}
ForegroundNegative={{dangerRgb}}
ForegroundNeutral={{accentRgb}}
ForegroundPositive={{successRgb}}

[Colors:Selection]
BackgroundNormal={{accentRgb}}
BackgroundAlternate={{accentHoverRgb}}
DecorationFocus={{accentRgb}}
DecorationHover={{accentHoverRgb}}
ForegroundNormal={{accentTextRgb}}
ForegroundActive={{accentTextRgb}}
ForegroundInactive={{accentTextRgb}}
ForegroundLink={{accentTextRgb}}
ForegroundVisited={{accentTextRgb}}
ForegroundNegative={{accentTextRgb}}
ForegroundNeutral={{accentTextRgb}}
ForegroundPositive={{accentTextRgb}}

[Colors:Tooltip]
BackgroundNormal={{surfaceRgb}}
BackgroundAlternate={{windowRgb}}
DecorationFocus={{accentRgb}}
DecorationHover={{accentHoverRgb}}
ForegroundNormal={{textRgb}}
ForegroundActive={{accentRgb}}
ForegroundInactive={{mutedRgb}}
ForegroundLink={{accentRgb}}
ForegroundVisited={{subtextRgb}}
ForegroundNegative={{dangerRgb}}
ForegroundNeutral={{accentRgb}}
ForegroundPositive={{successRgb}}

[Colors:Complementary]
BackgroundNormal={{windowRgb}}
BackgroundAlternate={{backgroundRgb}}
DecorationFocus={{accentRgb}}
DecorationHover={{accentHoverRgb}}
ForegroundNormal={{textRgb}}
ForegroundActive={{accentRgb}}
ForegroundInactive={{mutedRgb}}
ForegroundLink={{accentRgb}}
ForegroundVisited={{subtextRgb}}
ForegroundNegative={{dangerRgb}}
ForegroundNeutral={{accentRgb}}
ForegroundPositive={{successRgb}}

[Colors:Header]
BackgroundNormal={{windowRgb}}
BackgroundAlternate={{backgroundRgb}}
DecorationFocus={{accentRgb}}
DecorationHover={{accentHoverRgb}}
ForegroundNormal={{textRgb}}
ForegroundActive={{accentRgb}}
ForegroundInactive={{mutedRgb}}
ForegroundLink={{accentRgb}}
ForegroundVisited={{subtextRgb}}
ForegroundNegative={{dangerRgb}}
ForegroundNeutral={{accentRgb}}
ForegroundPositive={{successRgb}}
