/* Generated by sol-shell from export/wofi.css.tpl. Edit the template, not this
   file: it is rewritten whenever the theme changes. Use it with
   wofi --show drun --style ~/.local/state/theme/wofi.css */

window {
    margin: 0;
    border: 2px solid {{border}};
    border-radius: 12px;
    background-color: {{backgroundAlpha}};
    font-size: 14px;
}

#outer-box {
    margin: 6px;
    background-color: transparent;
    border: 2px solid {{border}};
}

#input {
    margin: 6px;
    padding: 8px 12px;
    border-radius: 8px;
    background-color: {{surface}};
    background-image: none;
    color: {{text}};
    box-shadow: none;
}

#input:focus {
    border-color: {{accent}};
    box-shadow: none;
}

#scroll {
    margin: 0 6px 6px 6px;
    background-color: transparent;
}

#inner-box {
    background-color: transparent;
}

#entry {
    padding: 6px 10px;
    border-radius: 8px;
    background-color: transparent;
}

#entry:selected {
    background-color: {{accent}};
    outline: none;
}

#text {
    margin-left: 8px;
    color: {{text}};
}

#text:selected {
    color: {{accentText}};
}

#img {
    margin-right: 4px;
}
