/* Generated by sol-shell from export/zen-userChrome.css.tpl. Edit the template,
   not this file: it is rewritten whenever the theme changes. Zen reads it as
   chrome/userChrome.css in the profile (a link to this file, made by
   export/zen-setup.sh) and only at startup, so restart Zen after a theme change.

   Zen builds its colors from a few variables. Most can be set on :root, but Zen
   sets the main background as an inline style on two elements, so those are set
   on the elements themselves; !important wins over an inline style. */

:root {
    color-scheme: {{scheme}} !important;
    --toolbar-color-scheme: {{scheme}} !important;
    --toolbox-textcolor: {{text}} !important;
    --zen-primary-color: {{accent}} !important;

    --zen-colors-primary: {{accent}} !important;
    --zen-colors-secondary: {{surface}} !important;
    --zen-colors-tertiary: {{window}} !important;
    --zen-colors-hover-bg: {{accentHover}} !important;
    --zen-colors-primary-foreground: {{accent}} !important;
    --zen-colors-border: {{border}} !important;
    --zen-colors-border-contrast: {{border}} !important;
    --zen-colors-input-bg: {{surface}} !important;

    --zen-toolbar-element-bg: {{surface}} !important;
    --zen-toolbar-element-bg-hover: {{border}} !important;
    --zen-urlbar-background: {{surface}} !important;
    --zen-dialog-background: {{window}} !important;
    --arrowpanel-background: {{window}} !important;
    --arrowpanel-color: {{text}} !important;
    --arrowpanel-border-color: {{border}} !important;
    --toolbar-field-background-color: {{surface}} !important;
    --toolbar-field-color: {{text}} !important;
    --toolbar-field-focus-color: {{text}} !important;
    --toolbar-field-focus-background-color: {{window}} !important;
    --link-color: {{accent}} !important;

    --tab-text-color: {{subtext}} !important;
    --tab-text-color-hover: {{text}} !important;
    --tab-text-color-selected: {{text}} !important;
}

#zen-browser-background {
    --zen-main-browser-background: {{backgroundAlpha}} !important;
}

#zen-toolbar-background {
    --zen-main-browser-background-toolbar: {{backgroundAlpha}} !important;
}

/* the big floating search box (new tab, Ctrl+L) sets its own background */
#urlbar[breakout-extend] .urlbar-background {
    --zen-urlbar-background-base: {{window}} !important;
    --zen-urlbar-background-transparent: {{window}} !important;
    background-color: {{window}} !important;
}

#urlbar[breakout-extend] {
    color: {{text}} !important;
}

#urlbar .urlbar-input::placeholder {
    color: {{muted}} !important;
    opacity: 1 !important;
}

/* the sidebar's labels ("Space", "New Tab") take their color from here */
#navigator-toolbox {
    color: {{text}} !important;
}

#tabs-newtab-button:not([in-urlbar="true"]),
.zen-current-workspace-indicator-name {
    color: {{subtext}} !important;
}

/* the toolbar icons (menu, sidebar, back, forward, reload) in the accent color.
   Every button sets this variable itself, so it has to be set on the buttons. */
#navigator-toolbox,
#navigator-toolbox .toolbarbutton-1,
#navigator-toolbox .urlbar-page-action,
#navigator-toolbox .identity-box-button {
    --toolbarbutton-icon-fill: {{accent}} !important;
    --toolbarbutton-icon-fill-attention: {{accent}} !important;
}
