// Generated by sol-shell from export/zen-user.js.tpl. Edit the template, not this
// file: it is rewritten whenever the theme changes. Zen reads it as the profile's
// user.js (a link to this file, made by export/zen-setup.sh) at every startup.

// let userChrome.css / userContent.css be read at all (off by default)
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);

// what websites are told about the preferred color scheme
// (0 = dark, 1 = light): they follow the theme, in this case {{scheme}}
user_pref("layout.css.prefers-color-scheme.content-override", {{contentScheme}});

// the browser's own toolbar and sidebar text/icons: without this they follow the
// system theme (dark here), which makes them unreadable on a light theme
user_pref("browser.theme.toolbar-theme", {{contentScheme}});
user_pref("browser.theme.content-theme", {{contentScheme}});
