/* Generated by sol-shell from export/zen-userContent.css.tpl. Edit the template,
   not this file: it is rewritten whenever the theme changes. Zen reads it as
   chrome/userContent.css in the profile (a link to this file) and only at
   startup. It colors Zen's own pages (about:newtab, about:preferences, ...);
   websites are not touched. */

@-moz-document url-prefix("about:"), url-prefix("chrome://") {
    :root {
        color-scheme: {{scheme}} !important;

        --in-content-page-color: {{text}} !important;
        --in-content-page-background: {{background}} !important;
        --in-content-text-color: {{text}} !important;
        --in-content-deemphasized-text: {{muted}} !important;
        --in-content-box-background: {{window}} !important;
        --in-content-box-background-hover: {{surface}} !important;
        --in-content-box-border-color: {{border}} !important;
        --in-content-border-color: {{border}} !important;
        --in-content-item-hover: {{surface}} !important;
        --in-content-item-selected: {{accent}} !important;
        --in-content-item-selected-text: {{accentText}} !important;
        --in-content-accent-color: {{accent}} !important;
        --in-content-primary-button-background: {{accent}} !important;
        --in-content-primary-button-background-hover: {{accentHover}} !important;
        --in-content-primary-button-text-color: {{accentText}} !important;
        --in-content-button-background: {{surface}} !important;
        --in-content-button-text-color: {{text}} !important;

        --background-color-canvas: {{background}} !important;
        --background-color-box: {{window}} !important;
        --text-color: {{text}} !important;
        --text-color-deemphasized: {{muted}} !important;
        --border-color: {{border}} !important;
        --link-color: {{accent}} !important;
        --color-accent-primary: {{accent}} !important;
        --zen-colors-tertiary: {{background}} !important;
    }

    body {
        background-color: {{background}} !important;
        color: {{text}} !important;
    }
}
